language: ruby
os: osx
env: OSX=10.11
osx_image: xcode7.3
rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - sudo chown -R $USER $(brew --repo)
  - git -C $(brew --repo) reset --hard origin/master
  - git -C $(brew --repo) clean -qxdff
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
  - brew update
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew/homebrew-nginx
  - cd $(brew --repo)/Library/Taps/homebrew/homebrew-nginx
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/homebrew/homebrew-nginx"
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 4096
  
script:
  - brew test-bot

notifications:
  email:
    on_success: never
    on_failure: always
